### ISSUE TITLE
Code abstraction: Nicholas

### ISSUE THREAD

**Issue by mdkbmi** [UBC-MDS/Car_Evaluation_Analysis#45]
* Download data
* Data validation
* Train/test split

**Comment by mdkbmi** [comment]
Environment file:
* `ucimlrepo` dependency not added to `environment.yaml`; was able to run `conda install ucimlrepo` in Terminal on my own

Command ran: `python scripts/download_data.py --data-to data/raw`
* Noticed that there are redundant files in `data/raw` (files aside from `car_data_raw.csv`), would it be better if the rest of the files are removed?

Command ran: `python scripts/split_n_preprocess.py --raw-data data/raw/car_data_raw.csv --data-to data/processed --preprocessor-to results/models`
* No issues

**Comment by nvarabioff** [comment]
- Added ucimlrepo to dependencies so that is available in the docker container
- removed redundant raw files
