### ISSUE TITLE
Feedback from milestone1

### ISSUE THREAD

**Issue by mdkbmi** [UBC-MDS/Car_Evaluation_Analysis#83]
Abstract/Summary
- Does not clearly state the question being asked.
- Does not discuss importance and limitations of findings.

Introduction
- Did not clearly identify the question being asked, or the question was not clear in some way.
- Only partially explains why this problem is important or interesting. More elaboration is needed to motivate the problem.
- Can you clarify what "acceptability" means in the context of your question? Why do buyers need help evaluating the quality of a car based on its attributes? Is that hard for the general public?

Methods
- Important methodology descriptions missing (e.g., did not explain in narrative what metric was being used for model parameter optimization).
- You did not explain in narrative what metric was being used for model parameter optimization - why did you choose the range you chose for gamma and C?
Results
- You did not explain in narrative what metric was being used for model parameter optimization - why did you choose the range you chose for gamma and C?
- You are doing multiclass classification but only report one overall test score (which I think is accuracy, but you should actually mention that). You should at a minimum look at a confusion matrix.

Discussion
- Discussion of results in incorrect in some ways with respect to the question being asked.
- For multiclass classification, you should report on more than one overall test score to link back to your original question.

References
- There are references at the end of the report, but they are not referred to in the narrative.

Spelling and Grammar
- There were just a couple spelling or grammatical errors. They did not impact the understanding of the document.

Project GitHub repository and workflow
- GitHub issues were rarely used for project communication.
- You should use more issues (and more detailed ones) to communicate with each other.

**Comment by nvarabioff** [comment]
These have all been addressed
